

[metadata]
name = math_operations_kseahtan
version = 1.0.0
author = Tan Kim Seah
description = An interactive terminal calculator with basic and advanced math operations.
long_description = file: README.md
long_description_content_type = text/markdown
classifiers =
    Programming Language :: Python :: 3
    Operating System :: OS Independent

[options]
python_requires = >=3.8
packages = find:

[options.packages.find]
include =
    basic*
    advanced*

[options.entry_points]
console_scripts =
    run-calculator = calculate:start_calculator


